/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountItem: typeof import('./components/Sidebar/AccountItem.vue')['default']
    AccountPreview: typeof import('./components/Sidebar/AccountPreview.vue')['default']
    AuthModal: typeof import('./components/Auth/AuthModal.vue')['default']
    BaseInputField: typeof import('./components/FormFields/BaseInputField.vue')['default']
    BaseVideoPlayer: typeof import('./components/VideoPlayer/BaseVideoPlayer.vue')['default']
    ButtonBase: typeof import('./components/ButtonBase.vue')['default']
    CardFollowItem: typeof import('./components/CardFollowItem.vue')['default']
    CardVideoItem: typeof import('./components/CardVideoItem.vue')['default']
    DiscoverList: typeof import('./components/Sidebar/DiscoverList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormBody: typeof import('./components/Auth/FormBody.vue')['default']
    Hashtag: typeof import('./components/Hashtag.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconBase: typeof import('./components/IconBase.vue')['default']
    ImageBase: typeof import('./components/ImageBase.vue')['default']
    Menu: typeof import('./components/Sidebar/Menu.vue')['default']
    MenuItemLink: typeof import('./components/Sidebar/MenuItemLink.vue')['default']
    ModalBase: typeof import('./components/ModalBase.vue')['default']
    ModalShortcut: typeof import('./components/ModalShortcut.vue')['default']
    NewsFeed: typeof import('./components/NewsFeed.vue')['default']
    OptionBody: typeof import('./components/Auth/OptionBody.vue')['default']
    PopperHeader: typeof import('./components/Popper/PopperMenu/PopperHeader.vue')['default']
    PopperMenu: typeof import('./components/Popper/PopperMenu/PopperMenu.vue')['default']
    PopperMenuItem: typeof import('./components/Popper/PopperMenu/PopperMenuItem.vue')['default']
    PopperWrapper: typeof import('./components/Popper/PopperWrapper.vue')['default']
    QrBody: typeof import('./components/Auth/QrBody.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrubber: typeof import('./components/Scrubber.vue')['default']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SeekBar: typeof import('./components/VideoPlayer/SeekBar.vue')['default']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    SuggestedList: typeof import('./components/Sidebar/SuggestedList.vue')['default']
    SwitchBase: typeof import('./components/SwitchBase.vue')['default']
    Tab: typeof import('./components/Tabs/Tab.vue')['default']
    TabList: typeof import('./components/Tabs/TabList.vue')['default']
    TabPanel: typeof import('./components/Tabs/TabPanel.vue')['default']
    TabPanels: typeof import('./components/Tabs/TabPanels.vue')['default']
    Tabs: typeof import('./components/Tabs/Tabs.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    VideoOverlay: typeof import('./components/VideoOverlay.vue')['default']
    Volume: typeof import('./components/Volume.vue')['default']
    VolumeSlider: typeof import('./components/VideoPlayer/VolumeSlider.vue')['default']
  }
}
